import { CATEGORIES, type GauntletFight, type PokemonEntry } from './types.ts'

export interface GameData {
  entries: PokemonEntry[]
  gauntlet: GauntletFight[]
}

/** `no-cache` makes the browser revalidate, so a new release never runs against old cached data. */
const getJson = async <T>(url: string): Promise<T> => {
  const res = await fetch(url, { cache: 'no-cache' })
  if (!res.ok) throw new Error(`Failed to load ${url}: ${res.status}`)
  return (await res.json()) as T
}

/** Data generated by a different version of the pipeline would silently break slot rules, so refuse it. */
function assertCurrent(entries: readonly PokemonEntry[]): void {
  for (const e of entries) {
    const known = (CATEGORIES as readonly string[]).includes(e.category)
    if (!known || (e.category === 'legend' && !e.legendKind)) {
      throw new Error(`The game data is out of date (${e.name}). Please reload the page.`)
    }
  }
}

export async function loadData(base: string = import.meta.env.BASE_URL): Promise<GameData> {
  const [entries, gauntlet] = await Promise.all([
    getJson<PokemonEntry[]>(`${base}data/pokemon.json`),
    getJson<GauntletFight[]>(`${base}data/gauntlet.json`),
  ])
  assertCurrent(entries)
  return { entries, gauntlet }
}
